export type DateDisplayType =
  'year'
  | 'year-month'
  | 'year-month-day'
  | 'year-month-day-hours'
  | 'year-month-day-hours-minutes'
  | 'year-month-day-hours-minutes-seconds'
  | 'year-month-day-hours-minutes-seconds-milliseconds'
  | 'hours'
  | 'hours-minutes'
  | 'hours-minutes-seconds'
  | 'hours-minutes-seconds-milliseconds';

export type TimeDisplayType =
  'weeks'
  | 'weeks-days'
  | 'weeks-days-hours'
  | 'weeks-days-hours-minutes'
  | 'weeks-days-hours-minutes-seconds'
  | 'weeks-days-hours-minutes-seconds-milliseconds'
  | 'days'
  | 'days-hours'
  | 'days-hours-minutes'
  | 'days-hours-minutes-seconds'
  | 'days-hours-minutes-seconds-milliseconds'
  | 'hours'
  | 'hours-minutes'
  | 'hours-minutes-seconds'
  | 'hours-minutes-seconds-milliseconds'
  | 'minutes'
  | 'minutes-seconds'
  | 'minutes-seconds-milliseconds'
  | 'seconds'
  | 'seconds-milliseconds'
  | 'milliseconds';
