import { lazy } from 'react';

export const AccountCircleIcon = lazy(() => import('./AccountCircleIcon').then(module => ({ default: module.AccountCircleIcon })));
export const AcuteIcon = lazy(() => import('./AcuteIcon').then(module => ({ default: module.AcuteIcon })));
export const AddIcon = lazy(() => import('./AddIcon').then(module => ({ default: module.AddIcon })));
export const AdminPanelSettingsIcon = lazy(() => import('./AdminPanelSettingsIcon').then(module => ({ default: module.AdminPanelSettingsIcon })));
export const AlarmIcon = lazy(() => import('./AlarmIcon').then(module => ({ default: module.AlarmIcon })));
export const AppsIcon = lazy(() => import('./AppsIcon').then(module => ({ default: module.AppsIcon })));
export const ArrowBackIcon = lazy(() => import('./ArrowBackIcon').then(module => ({ default: module.ArrowBackIcon })));
export const ArrowDownwardIcon = lazy(() => import('./ArrowDownwardIcon').then(module => ({ default: module.ArrowDownwardIcon })));
export const ArrowDropDownIcon = lazy(() => import('./ArrowDropDownIcon').then(module => ({ default: module.ArrowDropDownIcon })));
export const ArrowDropUpIcon = lazy(() => import('./ArrowDropUpIcon').then(module => ({ default: module.ArrowDropUpIcon })));
export const ArrowForwardIcon = lazy(() => import('./ArrowForwardIcon').then(module => ({ default: module.ArrowForwardIcon })));
export const ArrowLeftIcon = lazy(() => import('./ArrowLeftIcon').then(module => ({ default: module.ArrowLeftIcon })));
export const ArrowRightIcon = lazy(() => import('./ArrowRightIcon').then(module => ({ default: module.ArrowRightIcon })));
export const ArrowUpwardIcon = lazy(() => import('./ArrowUpwardIcon').then(module => ({ default: module.ArrowUpwardIcon })));
export const ArticleIcon = lazy(() => import('./ArticleIcon').then(module => ({ default: module.ArticleIcon })));
export const AssignmentIcon = lazy(() => import('./AssignmentIcon').then(module => ({ default: module.AssignmentIcon })));
export const AttachFileIcon = lazy(() => import('./AttachFileIcon').then(module => ({ default: module.AttachFileIcon })));
export const AttachmentIcon = lazy(() => import('./AttachmentIcon').then(module => ({ default: module.AttachmentIcon })));
export const AutorenewIcon = lazy(() => import('./AutorenewIcon').then(module => ({ default: module.AutorenewIcon })));
export const LoadingIcon = lazy(() => import('./AutorenewIcon').then(module => ({ default: module.LoadingIcon })));
export const BadgeIcon = lazy(() => import('./BadgeIcon').then(module => ({ default: module.BadgeIcon })));
export const BoltIcon = lazy(() => import('./BoltIcon').then(module => ({ default: module.BoltIcon })));
export const BubbleChartIcon = lazy(() => import('./BubbleChartIcon').then(module => ({ default: module.BubbleChartIcon })));
export const BuildIcon = lazy(() => import('./BuildIcon').then(module => ({ default: module.BuildIcon })));
export const CalendarMonthIcon = lazy(() => import('./CalendarMonthIcon').then(module => ({ default: module.CalendarMonthIcon })));
export const CalendarTodayIcon = lazy(() => import('./CalendarTodayIcon').then(module => ({ default: module.CalendarTodayIcon })));
export const CheckIcon = lazy(() => import('./CheckIcon').then(module => ({ default: module.CheckIcon })));
export const ChecklistIcon = lazy(() => import('./ChecklistIcon').then(module => ({ default: module.ChecklistIcon })));
export const CloseIcon = lazy(() => import('./CloseIcon').then(module => ({ default: module.CloseIcon })));
export const CloudUploadIcon = lazy(() => import('./CloudUploadIcon').then(module => ({ default: module.CloudUploadIcon })));
export const CodeIcon = lazy(() => import('./CodeIcon').then(module => ({ default: module.CodeIcon })));
export const ContactsIcon = lazy(() => import('./ContactsIcon').then(module => ({ default: module.ContactsIcon })));
export const ContentCopyIcon = lazy(() => import('./ContentCopyIcon').then(module => ({ default: module.ContentCopyIcon })));
export const DarkModeIcon = lazy(() => import('./DarkModeIcon').then(module => ({ default: module.DarkModeIcon })));
export const DashboardIcon = lazy(() => import('./DashboardIcon').then(module => ({ default: module.DashboardIcon })));
export const DeleteIcon = lazy(() => import('./DeleteIcon').then(module => ({ default: module.DeleteIcon })));
export const DemographyIcon = lazy(() => import('./DemographyIcon').then(module => ({ default: module.DemographyIcon })));
export const DescriptionIcon = lazy(() => import('./DescriptionIcon').then(module => ({ default: module.DescriptionIcon })));
export const DownloadIcon = lazy(() => import('./DownloadIcon').then(module => ({ default: module.DownloadIcon })));
export const DraftIcon = lazy(() => import('./DraftIcon').then(module => ({ default: module.DraftIcon })));
export const DragIndicatorIcon = lazy(() => import('./DragIndicatorIcon').then(module => ({ default: module.DragIndicatorIcon })));
export const EditIcon = lazy(() => import('./EditIcon').then(module => ({ default: module.EditIcon })));
export const EditNoteIcon = lazy(() => import('./EditNoteIcon').then(module => ({ default: module.EditNoteIcon })));
export const ErrorIcon = lazy(() => import('./ErrorIcon').then(module => ({ default: module.ErrorIcon })));
export const EventIcon = lazy(() => import('./EventIcon').then(module => ({ default: module.EventIcon })));
export const ExpandLessIcon = lazy(() => import('./ExpandLessIcon').then(module => ({ default: module.ExpandLessIcon })));
export const ExpandMoreIcon = lazy(() => import('./ExpandMoreIcon').then(module => ({ default: module.ExpandMoreIcon })));
export const ExtensionIcon = lazy(() => import('./ExtensionIcon').then(module => ({ default: module.ExtensionIcon })));
export const FilterListIcon = lazy(() => import('./FilterListIcon').then(module => ({ default: module.FilterListIcon })));
export const FolderIcon = lazy(() => import('./FolderIcon').then(module => ({ default: module.FolderIcon })));
export const FolderManagedIcon = lazy(() => import('./FolderManagedIcon').then(module => ({ default: module.FolderManagedIcon })));
export const FolderOpenIcon = lazy(() => import('./FolderOpenIcon').then(module => ({ default: module.FolderOpenIcon })));
export const ForwardIcon = lazy(() => import('./ForwardIcon').then(module => ({ default: module.ForwardIcon })));
export const FullscreenExitIcon = lazy(() => import('./FullscreenExitIcon').then(module => ({ default: module.FullscreenExitIcon })));

export * from './FullscreenIcon';
export * from './Globe';
export * from './GroupAddIcon';
export * from './GroupIcon';
export * from './HardDriveIcon';
export * from './HelpIcon';
export * from './HistoryIcon';
export * from './HomeIcon';
export * from './HomeStorageIcon';
export * from './InfoIcon';
export * from './InvertColorsIcon';
export * from './LanguageIcon';
export * from './LeaderboardIcon';
export * from './LibraryBooksIcon';
export * from './LightModeIcon';
export * from './LinkIcon';
export * from './ListIcon';
export * from './LocationOnIcon';
export * from './LockIcon';
export * from './LockPersonIcon';
export * from './LoginIcon';
export * from './LogoutIcon';
export * from './MailIcon';
export * from './ManageAccountsIcon';
export * from './ManageSearchIcon';
export * from './ManufacturingIcon';
export * from './MenuBookIcon';
export * from './MoreTimeIcon';
export * from './NavigateBeforeIcon';
export * from './NavigateNextIcon';
export * from './NewReleasesIcon';
export * from './NoteAddIcon';
export * from './NoteIcon';
export * from './OpenInNewIcon';
export * from './PageInfoIcon';
export * from './PaletteIcon';
export * from './PendingActionsIcon';
export * from './PendingIcon';
export * from './PersonIcon';
export * from './PhotoLibraryIcon';
export * from './PictureAsPdfIcon';
export * from './PlayArrowIcon';
export * from './PlayCircleIcon';
export * from './PostAddIcon';
export * from './PreviewIcon';
export * from './PublicIcon';
export * from './PublishIcon';
export * from './RedoIcon';
export * from './RefreshIcon';
export * from './ReplyAllIcon';
export * from './ReplyIcon';
export * from './SaveIcon';
export * from './ScheduleIcon';
export * from './SchoolIcon';
export * from './SearchIcon';
export * from './SendIcon';
export * from './SettingsAlertIcon';
export * from './SettingsIcon';
export * from './SettingsSuggestIcon';
export * from './ShareIcon';
export * from './SpeedIcon';
export * from './StopCircleIcon';
export * from './StorageIcon';
export * from './SupportAgentIcon';
export * from './SyncIcon';
export * from './TaskIcon';
export * from './TimerIcon';
export * from './TrendingUpIcon';
export * from './UndoIcon';
export * from './UpdateIcon';
export * from './VerticalSplitIcon';
export * from './ViewCozyIcon';
export * from './ViewHeadlineIcon';
export * from './VisibilityIcon';
export * from './VisibilityOffIcon';
export * from './VoidIcon';
export * from './WarningIcon';
